apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170590106
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170590106
    app.kubernetes.io/part-of: test-app-170590106
  name: java-quarkus-170590106
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170590106
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170590106
    spec:
      containers:
      - image: quay.io/hacdev/amhu7rvx-tenant/test-app-170590106/java-quarkus-170590106@sha256:9c08194c56b2d500bd83244de0f7493f642414030b66245a5e84bfe280d47121
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
